const legacyAssetRoot='https://rcw3-pear-gnome-club.vincenzoweb3.chatgpt.site';
const questions=[
['Instinct under uncertainty','A moonlit gate opens where no path existed. What do you do first?',['Invite the nearest gnomes and enter together','Study the runes, hinges, and hidden mechanism','Step through before the gate changes its mind','Listen to the roots and spores around it']],
['Joyful use of time','The club gives you one enchanted Saturday. Which plan feels irresistible?',['Planting an orchard, trading seeds, and cooking the harvest','Building a strange device or launching a digital experiment','Hiking somewhere wild and documenting what we discover','Hosting a feast, open mic, game night, or creative jam']],
['Chaos and contribution','A promising club project is beautifully chaotic. Where do you naturally land?',['I create the plan, roles, timeline, and finish line','I make the idea exciting enough that people join','I connect the right people and let the network grow','I question the premise and find the unexpected version']],
['Knowledge to share','Which kind of knowledge do you most enjoy sharing?',['How to grow, cook, heal, preserve, or care for living things','How to build, code, invest, repair, or improve a system','Stories, art, music, culture, humor, or a different perspective','History, hard-won lessons, safety, or what others overlook']],
['Conflict magic','The fire circle falls silent after a disagreement. What magic do you use?',['Make sure every person feels heard before solving anything','Name the hard truth clearly and respectfully','Turn tension into a practical agreement and next step','Shift the angle with humor or a surprising third option']],
['Support needed','What kind of club support would change your season most?',['Seeds, land access, growing supplies, or hands-on learning','Collaborators, technology, funding pathways, or project structure','Belonging, encouragement, gatherings, or people who truly get me','Fresh inspiration, travel, research, or permission to reinvent']],
['Scarcity and stewardship','A rare pear tree bears only eight fruits. What is the wisest move?',['Save seed, document it, and build a plan for future harvests','Share slices now so every member tastes the wonder','Study it, cross-pollinate it, and test what else it can become','Trade one fruit for another rare treasure and expand the map']],
['Learning style','How do you prefer to learn something unfamiliar?',['Hands in the soil beside someone experienced','A clear guide, examples, and time to practice privately','A playful challenge where we learn by trying','A conversation that connects it to people and purpose']],
['Invitation','Which invitation would you answer fastest?',['Help us plant, harvest, cook, or restore a living place','Help us build a tool, prototype, website, or member box','Help us host a gathering, welcome members, or teach a workshop','Help us create a film, campaign, story, or mystery hunt']],
['Risk and courage','The clan must choose between a safe path and an untested shortcut. You…',['Protect the group and improve the safe path','Test the shortcut with a small scout team first','Take the shortcut—the moment calls for courage','Look for the third path hidden by the argument']],
['Pace','What pace helps you contribute your best work?',['A steady recurring role I can depend on','Short, exciting missions with a visible finish','Flexible collaboration when inspiration and people align','Seasonal gatherings with time to reflect between them']],
['World journey','Which treasure would you bring home from a world journey?',['A living seed found nowhere else','A beautifully engineered tool with no known purpose','A song, recipe, or story entrusted to you by a community','A protective artifact earned through a dangerous trial']],
['Trust and budget','If the club handed you a small budget and full trust, what would appear?',['A micro-garden, seed library, or food-sharing project','A useful product, digital tool, or member system','A gathering people talk about for months','An artwork, film, quest, or story that changes the club’s lore']],
['Growth and legacy','One year from now, which sentence would make you proudest?',['We grew food, skills, and confidence together','We built something durable that members use every week','We became a network where opportunities move to the right people','We created a culture and story nobody else could imitate']]
];
const members=[
['Bombshell','bombshell'],['Zaal','zaal'],['Fordenand','fordenand'],['Maahaa','maahaa'],['Jeremy Two','jeremy-two'],['Lady Never Scared','lady-never-scared'],['Baka','baka'],['KuyaMark','kuyamark'],['Yeeki','yeeki'],['Cel3stial Chipz','cel3stial-chipz'],['YungJarritos','yungjarritos'],['SicarioBaby','sicariobaby'],['Old Sailor','old-sailor'],['Crypto Paulie','crypto-paulie'],['HostXweb3','hostxweb3'],['Bagelism','bagelism'],['Giddy','giddy'],['Kerry Cook','kerry-cook'],['KnowME','knowme'],['O$','o-dollar'],['Mulberry Tree App','mulberry-tree-app'],['Philheal','philheal'],['KingDankKush','kingdankkush']
];
const realmResults=[
['Middle Forest','🌳','Stewardship, balance, and the living center of the grove.'],
['Ember Hollow','🐉','Flame, power, creation, and bold transformation.'],
['Hollow Woods','🌙','Death, spirit, truth, and the wisdom of what remains.'],
['Spore Grove','🍄','Connection, mind, network, and shared possibility.'],
['Ironbark Frontier','🛡️','Protection, endurance, boundaries, and brave exploration.'],
['The Violet Veil','🪞','Perspective, mystery, mischief, and unexpected turns.'],
['Light Realm','✨','Joy, welcome, clarity, and the energy that lifts a room.'],
['Steam Realm','⚙️','Systems, tools, invention, and useful things made real.']
];
let currentMember=0;
const $=selector=>document.querySelector(selector);
const toast=(message)=>{const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),3200)};
function renderMembers(){const list=$('#member-list');list.innerHTML=members.map((member,index)=>'<button class="member-button '+(index===currentMember?'active':'')+'" data-member="'+index+'"><span>'+String(index+1).padStart(2,'0')+'</span>'+member[0]+'</button>').join('');list.querySelectorAll('[data-member]').forEach(button=>button.addEventListener('click',()=>showMember(Number(button.dataset.member))))}
function showMember(index){currentMember=(index+members.length)%members.length;const [name,slug]=members[currentMember];$('#member-image').src=legacyAssetRoot+'/members/'+slug+'.png';$('#member-image').alt='3D portrait of '+name;$('#member-number').textContent=String(currentMember+1).padStart(2,'0');$('#member-name').textContent=name;$('#member-count').textContent=(currentMember+1)+' / '+members.length;renderMembers()}
function renderTravelers(){const travelers=JSON.parse(localStorage.getItem('gpc-travelers')||'[]');const list=$('#traveler-list');if(!travelers.length){list.innerHTML='<p class="empty-note">No footsteps yet. Be the first gnome through the gate.</p>';return}list.innerHTML=travelers.slice(-8).reverse().map(item=>'<div class="traveler"><strong>'+escapeHtml(item.alias)+'</strong> · '+escapeHtml(item.realm)+'</div>').join('')}
function escapeHtml(text){return String(text).replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[character]))}
function realmFor(answers){const scores=[0,0,0,0,0,0,0,0];answers.forEach((answer,index)=>{const value=(answer+index)%8;scores[value]+=2;scores[(value+3)%8]+=index%3===0?1:0});let best=0;scores.forEach((score,index)=>{if(score>scores[best])best=index});return realmResults[best]}
function renderSurvey(){const root=$('#survey-root');let answers=[];let step=0;const aliasInput=$('#alias');$('#start-survey').addEventListener('click',()=>{step=0;answers=[];showQuestion()});
function showQuestion(){const [label,prompt,options]=questions[step];root.innerHTML='<div class="question-wrap"><div class="question-meta"><span>Question '+(step+1)+' of '+questions.length+' · '+label+'</span><span>'+Math.round(step/questions.length*100)+'%</span></div><div class="progress"><i style="width:'+Math.round(step/questions.length*100)+'%"></i></div><h2>'+prompt+'</h2><div class="answer-grid">'+options.map((option,index)=>'<button class="answer" data-answer="'+index+'"><b>'+String.fromCharCode(65+index)+'</b><span>'+option+'</span></button>').join('')+'</div></div><div class="realm-map" aria-label="The eight realms">'+realmResults.map(item=>'<span>'+item[1]+' '+item[0]+'</span>').join('')+'</div>';root.querySelectorAll('[data-answer]').forEach(button=>button.addEventListener('click',()=>{answers.push(Number(button.dataset.answer));if(step<questions.length-1){step++;showQuestion()}else{showResult()}}))}
function showResult(){const result=realmFor(answers);const alias=(aliasInput?.value||'Unnamed traveler').trim()||'Unnamed traveler';const travelers=JSON.parse(localStorage.getItem('gpc-travelers')||'[]');travelers.push({alias,realm:result[0]});localStorage.setItem('gpc-travelers',JSON.stringify(travelers.slice(-20)));localStorage.setItem('gpc-result',JSON.stringify({alias,realm:result[0]}));localStorage.setItem('gpc-realm-credit','1');updateCredits();renderTravelers();root.innerHTML='<div class="result-card"><div><p class="eyebrow">Your path is open</p><h2>'+result[1]+' '+result[0]+'</h2><p>'+result[2]+'</p><div class="result-actions"><button class="button button-primary" id="retake">Take it again</button><a class="outline-button" href="#members">Meet the members</a></div></div><div class="result-symbol" aria-hidden="true">'+result[1]+'</div></div>';$('#retake').addEventListener('click',()=>{step=0;answers=[];showQuestion()})}}
function updateCredits(){const profile=localStorage.getItem('gpc-profile')?'1':'0';const realm=localStorage.getItem('gpc-realm-credit')?'1':'0';const growth=localStorage.getItem('gpc-growth-credit')?'5':'0';$('#credit-total').textContent=(Number(profile)+Number(realm)+Number(growth)).toFixed(2)}
document.addEventListener('DOMContentLoaded',()=>{renderMembers();showMember(0);renderTravelers();updateCredits();$('#member-prev').addEventListener('click',()=>showMember(currentMember-1));$('#member-next').addEventListener('click',()=>showMember(currentMember+1));$('#growth-task').addEventListener('click',()=>toast('Member discovery opens after your profile is complete.'));});
